package com.nardah.content;

/**
 * The activity log class.
 * @author Daniel
 */
public enum ActivityLog {
	/* Activities */
	BARROWS, FIGHT_CAVES, PEST_CONTROL, KOLODIONS_MINIGAME, CRYSTAL_CHEST, EASY_CLUE, MEDIUM_CLUE, HARD_CLUE, ELITE_CLUE,
	
	/* Bosses */
	SKOTIZO, GLOD, JUSTICAR, PORAZDIR, GANO, GALVEK, ZULRAH, CORPOREAL_BEAST, KING_BLACK_DRAGON, CHAOS_ELEMENTAL, CHAOS_FANATIC, CRAZY_ARCHAEOLOGIST, CALLISTO, SCORPIA, VENANTIS, VETION, KRAKEN, COMMANDER_ZILYANA, GENERAL_GRAARDOR, KRIL_TSUTSAROTH, KREE_ARRA, CERBERUS,
	
	/* Regular monsters */
	SKELETAL_WYVERN, ABYSSAL_DEMON, LIZARD_SHAMAN, GIANT_ROC, MITHRIL_DRAGON, DARK_BEAST, MAN, LAVA_DRAGON, VORKATH,
}
